server:
    port: 8769

eureka:
    client:
        service-url:
            defaultZone: http://occ:occ2018@localhost:8761/eureka/
#        # 获取服务注册状态的间隔时间
#        registry-fetch-interval-seconds: 5
    instance:
        instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
        prefer-ip-address: true

spring:
    application:
        name: occ-sci-gateway
    profiles:
        active: '@spring.profiles.active@'
    jmx:
        default-domain: ${spring.application.name}
    redis:
        host: 10.16.2.59
        port: 6379
        password: Occ2018
        database: 0
        lettuce:
            pool:
                max-idle: 10
                min-idle: 0
                max-active: 10
                max-wait: -1

zuul:
    sensitive-headers: Set-Cookie,Authorization
    ribbon-isolation-strategy: THREAD
    thread-pool:
        use-separate-thread-pools: true
        thread-pool-key-prefix: ${spring.application.name}
    routes:
        occ-cmpt:
            path: /occ-cmpt/**
            serviceId: occ-cmpt
        occ-base:
            path: /occ-base/**
            serviceId: occ-base
        occ-cr:
            path: /occ-cr/**
            serviceId: occ-cr
        occ-b2b-order:
            path: /occ-b2b-order/**
            serviceId: occ-b2b-order
        occ-b2b-buyer:
            path: /occ-b2b-buyer/**
            serviceId: occ-b2b-buyer
        occ-fee:
            path: /occ-fee/**
            serviceId: occ-fee
        occ-b2c:
            path: /occ-b2c/**
            serviceId: occ-b2c
        occ-stock:
            path: /occ-stock/**
            serviceId: occ-stock
        occ-purchase:
            path: /occ-purchase/**
            serviceId: occ-purchase
        occ-prom:
            path: /occ-prom/**
            serviceId: occ-prom
        occ-price:
            path: /occ-price/**
            serviceId: occ-price
        occ-settlement:
            path: /occ-settlement/**
            serviceId: occ-settlement
        occ-stl-b2c:
            path: /occ-stl-b2c/**
            serviceId: occ-stl-b2c
        occ-pay:
            path: /occ-pay/**
            serviceId: occ-pay
        occ-integration:
            path: /occ-integration/**
            serviceId: occ-integration
        occ-dispatch:
            path: /occ-dispatch/**
            serviceId: occ-dispatch
        occ-contract:
            path: /occ-contract/**
            serviceId: occ-contract
        occ-rebate:
            path: /occ-rebate/**
            serviceId: occ-rebate
        occ-plan:
            path: /occ-plan/**
            serviceId: occ-plan
        # 云审批
        occ-ys:
            path: /occ-ys/**
            serviceId: occ-ys
        # 服务云 - 基础档案
        fuwu-base:
            path: /fuwu-base/**
            serviceId: fuwu-base
        # 服务云 - 订单
        fuwu-order:
            path: /fuwu-order/**
            serviceId: fuwu-order
        # 服务云 - 经销商端
        fuwu-dealer:
            path: /fuwu-dealer/**
            serviceId: fuwu-dealer
        # 友销通 - start
        fmcg-occ-base-ext:
            path: /fmcg-occ-base-ext/**
            serviceId: fmcg-occ-base-ext
        fmcg-kb:
            path: /fmcg-kb/**
            serviceId: fmcg-kb
        fmcg-customer:
            path: /fmcg-customer/**
            serviceId: fmcg-customer
        fmcg-sales-target:
            path: /fmcg-sales-target/**
            serviceId: fmcg-sales-target
        fmcg-msg:
            path: /fmcg-msg/**
            serviceId: fmcg-msg
        fmcg-bpm:
            path: /fmcg-bpm/**
            serviceId: fmcg-bpm
        fmcg-visit:
            path: /fmcg-visit/**
            serviceId: fmcg-visit
        fmcg-act:
            path: /fmcg-act/**
            serviceId: fmcg-act
        fmcg-dynamic-object:
            path: /fmcg-dynamic-object/**
            serviceId: fmcg-dynamic-object
        fmcg-analysis:
            path: /fmcg-analysis/**
            serviceId: fmcg-analysis
        fmcg-cooperation-work:
            path: /fmcg-cooperation-work/**
            serviceId: fmcg-cooperation-work
        fmcg-visit-osd:
            path: /fmcg-visit-osd/**
            serviceId: fmcg-visit-osd
        fmcg-oppm:
            path: /fmcg-oppm/**
            serviceId: fmcg-oppm
        fmcg-yh-osd-web:
            path: /fmcg-yh-osd-web/**
            serviceId: fmcg-yh-osd-web
        fmcg-workbench:
            path: /fmcg-workbench/**
            serviceId: fmcg-workbench
        # 友销通 - end
        beauty-farm-agent:
            path: /beauty-farm-agent/**
            serviceId: beauty-farm-agent
    host:
        connect-timeout-millis: 10000
        socket-timeout-millis: 60000

hystrix:
    threadpool:
        default:
            coreSize: 100
            maximumSize: 2000
            allowMaximumSizeToDivergeFromCoreSize: true
            maxQueueSize: -1
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 60000

ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
#    # 服务列表刷新间隔，即Ribbon缓存时间
#    ServerListRefreshInterval: 2000

logging:
    # 日志文件路径
    file: /tmp/logs/${spring.application.name}/spring.log

management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: ALWAYS

# Swagger生成配置
swagger:
    butler:
        auto-generate-from-zuul-routes: true
        generate-routes:
            - occ-cmpt
            - occ-base
            - occ-cr
            - occ-b2b-order
            - occ-fee
            - occ-b2c
            - occ-stock
            - occ-purchase
            - occ-prom
            - occ-price
            - occ-settlement
            - occ-pay
            - occ-dispatch
            - occ-contract
            - occ-rebate
            - occ-plan
            - occ-ys
            - fuwu-base
            - fuwu-order
            - fuwu-dealer

auth:
    switch: true
    exclude-url: /**/gotoLogin,/**/bpmcallback/**


# CRM相关配置
fmcg:
    redis:
        host: 10.16.2.59
        port: 6379
        password: Occ2018
        database: 1
        pool:
            max-idle: 8
            min-idle: 0
            max-active: 8
            max-wait: -1


# S:sec,M：min,H:hour,D:day
session:
    time: 24
    timeUnit: H
